import FormComponent from "./Form";
export const Form = FormComponent;
import TabsComponent from "./Tabs";
export const Tabs = TabsComponent;
import FullPageLoaderComponent from "./FullPageLoader";
export const FullPageLoader = FullPageLoaderComponent;
import UserCardComponent from "./UserCard";
export const UserCard = UserCardComponent;
import ChatCardComponent from "./ChatCard";
export const ChatCard = ChatCardComponent;
import ChatCardLoadingComponent from "./ChatCard/ChatCardLoading";
export const ChatCardLoading = ChatCardLoadingComponent;
